pires/kubernetes-vagrant-coreos-cluster

- README.md
- Vagrantfile
These changes allow a user to put a .dockercfg into the same directory as the Vagrantfile and Vagrant will take care of provisioning the nodes.
> Added conditional .dockercfg provisioning

- .gitignore
- README.md
- Vagrantfile
- allow setting the .dockercfg location via the DOCKERCFG environment
variable. (defaults do ~/.dockercfg, which is where most people are
expected to have it, so it should just work out of the box).
- make the DOCKERCFG node provisioning automatic and inconditional, on
each startup.
- tweak docs.
- add ".dockercfg" to .gitignore _just_ in case...
Signed-off-by: António Meireles <antonio.meireles@reformi.st>
> tweak PR#21 (.dockercfg provisioning)

- node.yaml
lets spare as much bandwidth as we can. (only matters atm for cadvisor)
> only start docker in the minion nodes after the master's docker-cache is up

- README.md
- Add a `brew update` command before installing fleetctl to ensure
that we get the latest version. Without this, running `fleetctl
list-machines` will show a warning saying fleetctl is older than
the cluster it is communicating with.
- Add an `--endpoing` argument to the first `fleetctl` command to
ensure that it talks to the etcd endpoint in the VM and not the
localhost.
> Minor corrections to the README

- master.yaml
Hi,
i would like to install docker ui on my minions, but i could not run the pods with your setup. The allow_privileged flag must be set on the api-server as well.
Regards
Bernd
> fix privileged mode

- master.yaml
v1beta3 was not working because it was not getting passed in correctly.
> Add missing '\' for apiserver

- Vagrantfile
This prevents 2 errors when dns controller and service are already created.
This also prepares for windows-based provisioning:
- For windows (mingw) kubectl must be installed at coreos, because it needs *nix.
- When installing within coreos the commands may not return an error, that crashes the vagrant up process, so checking for availability is needed
> create dns replicationController and service only when uncreated

- README.md
- Vagrantfile
- master.yaml
- node.yaml
The Ethernet interface used by Flannel is hard-coded to `eth1` in 2 `.yaml` files, which works for VirtualBox but not for VMware Fusion --  `systemd` on CoreOS w/Fusion names the interface `ens34`.   An easy way to have this accommodate both hypervisors is via environment variable `FLANNEL_IF`.  Default is still `eth1`.
Tested successfully with the Kubernetes guestbook example app on Fusion 7.1.1.
> Specify Ethernet device name in environment variable

- Vagrantfile
On windows I got the following error message. Figured it should run as core.
==> master: Executing remote command "/bin/sh /home/core/kubectlsetup install"...
==> master: unlink:
==> master: cannot unlink '/root/.bash_profile'
==> master: : No such file or directory
==> master: Remote command execution finished.
The command "/bin/sh /home/core/kubectlsetup install" returned a failed exit code. The
error output is shown below:
unlink: cannot unlink '/root/.bash_profile': No such file or directory
> Make kubectlsetup run as user core.

- Vagrantfile
[problem] when we change the setting in the master.yaml or node.yaml and execute vagrant reload --provision, it always fails to reflect the setting updates in VM. we need to reload twice to reflect these change
[source] master.yaml /node.yaml will be copied as var/lib/coreos-vagrant/vagrantfile-user-data, and there's one service watch on the existence of this file. For the vagrant reload case, as the file is already existed, cloudinit will reflect the old version before it's updated when VM restart. It does not read the new file.
[solution] when halt or reload the vms, we should remove the vagrantfile-user-data in each VMs
> fix vagrant reload cannot update

- Vagrantfile
just as #98 dissussed, when user execute 'vagrant halt', the vagrantfile-use-data  will be removed, and when user execute 'vagrant up', the VM will be kept waiting.
[Solution] use REMOVE_VAGRANTFILE_USER_DATA_BEFORE_HALT to control the removal logic. by default, the removal will not happen. When user set the option on, then they need to add --provision when execute 'vagrant up / reload'
> by default, do not remove vagrantfile-user-data

- node.yaml
- As of etcd 2.0.11 (see here: https://github.com/coreos/etcd/releases/tag/v2.0.11)
the -advertise-client-urls option is mandatory.
> Add advertise-client-urls to etcd2 launch options.

- node.yaml
kubelets working directory is by default `/`
this patch changes the kubelets wd to /root/ where a
.dockercfg file is placed by the Vagrant script
> fixes pires/kubernetes-vagrant-coreos-cluster#97

- Vagrantfile
Mac version of `sed` utility requires to pass extension to work, while for Linux version this is optional. This small fix makes `sed` to work properly both on Mac and Linux
> Fix sed command line to work properly both on Mac Linux machines

- Vagrantfile
Add code to validate if VM IP address is already included in NO_PROXY env variable. This fix let avoid adding same IP address into NO_PROXY multiple times, for each vagrant provision.
> Fix adding VM IP addresses to NO_PROXY multiple times

- Vagrantfile
- master.yaml
`/tmp` is removed on VM `halt` so `kube-serviceaccount.key` needs to be stored in a permanent folder.
> Fixes #115

- README.md
- Vagrantfile
- master.yaml
- node.yaml
Fixes pires/kubernetes-vagrant-coreos-cluster#129
The name of the variable is DOCKER_OPTIONS instead of DOCKER_OPTS so it won't collide with users local environment settings.
> Added DOCKER_OPTIONS environment variable

- README.md
This patch rectifies the default values for master and minion
memory in README
> Rectifies default values in README

- Vagrantfile
This change adds necessary configuration so that VMware Fusion VMs properly reflect the memory and CPU directives specified - defaults or in env vars.
Tested Kubernetes guestbook sample app on Fusion 7.1.2 with following command; observed memory/CPU of running VMs reflected these directives:
`NODE_MEM=3000 NODE_CPUS=2 MASTER_MEM=2000 vagrant up`
> Make Fusion VMs honor specified memory and CPU settings.

- master.yaml
- node.yaml
Having proxy settings for the Kubernetes-api service creates problems, this configuration only uses proxy settings for the services that need it.
> Fixes for proxies in services

- master.yaml
- node.yaml
to reduce network overhead since vxlan is not needed when all nodes share the same L2 domain.
> Use host-gw instead of vxlan 

- Vagrantfile
Last night I was having an issue where my boxes were taking a while to come up due to slow interwebs, and the master would timeout trying to connect. Adding a configurable BOX_TIMEOUT_COUNT to increase the time it takes if needed.
> use optional env var BOX_TIMEOUT_COUNT 

- Vagrantfile
- plugins/dns/dns-controller.yaml.tmpl
- plugins/dns/dns-service.yaml
Kubernetes documentation points to creating kube-dns in the kube-system namespace. Should we try to match that pattern?
> Create kube-dns in kube-system namespace by default

- README.md
Hey, this PR add a comment for Windows user as they need to switch off a WindowsGit behavior.
We previously have added a .gitattributes file. But this one protect the repository, it doesn't change the update of all LF to CRLF for windows user with `core.autocrlf` set to `true` (the default behavior).
> Add CRLF to LF comment for windows users

- plugins/dns/dns-controller.yaml.tmpl
- plugins/dns/dns-service.yaml
- update skydns image to the version released for k8s 1.1.8
- update skydns rc yaml to reflect latest health check pods
https://github.com/kubernetes/kubernetes/blob/v1.1.8/cluster/addons/dns/skydns-rc.yaml.in
> SkyDNS Updates

- master.yaml
- node.yaml
Instead of downloading the binaries everytime vagrant up is done, do
a ConditionalPath to check for binaries.
This fixes #186
> Avoid download binaries on subsequent vagrant up

- README.md
- Vagrantfile
Duplicate of PR #193. Fixing committer email.
It is better to have the sync folders function set to false by default IMO. I introduced a flag to set this. Vagrant will copy synced_folders.yaml and go through mount points only if SYNC_FOLDERS is true.
> Flag to control sync folders

- .gitignore
- README.md
- Vagrantfile
Providers specified incorrectly in README. Expanded path for "synced_folders.yaml" in Vagrantfile so you can use vagrant commands outside of the repo directory.
> Fixes to README and Vagrantfile.

- Vagrantfile
- plugins/dns/dns-configmap.yaml
- plugins/dns/dns-deployment.yaml.tmpl
- plugins/dns/dns-service.yaml
According to [upstream](https://github.com/kubernetes/kubernetes/tree/v1.7.2/cluster/addons/dns).
This also fixes #237, as I've removed the `DNS_UPSTREAM_SERVERS` param.
> Upgrade 'kube-dns' to 1.14.4.

- Vagrantfile
Fixes issue when Kubernetes doesn't start on second and later boot cycles. `/vagrant/manifests/*.yaml` are copied to guest machines on every boot while the token replacement is done only on the first.
Fixes #243
> Perform token replacement on every boot

- .gitattributes
- Vagrantfile
Fix weird VM virtual hardware incompatibility.  The CoreOS VM wouldn't boot on Workstation without upgrading the virtual hardware... Something about AVX2 or something.  It can be passed in from the Vagrantfile.  This sets the virtual hardware to version 10, compatible with Fusion 6+, Workstation 10+ and ESXi 5.5+
This error could only be seen in the VMware logs:
```
This virtual machine requires AVX2 but AVX is not present.
```
Also, use .gitattributes to ensure we always checkout with proper line endings.
> Fixes for Windows

- Vagrantfile
- master.yaml
- node.yaml
- tls/master-kubeconfig.yaml
- tls/node-kubeconfig.yaml
The `--api-servers` argument was removed in 1.8 and deprecated long before in favor of kubeconfig
> Add kubernetes 1.8 compatibility

- manifests/node-proxy.yaml
- tls/node-kubeconfig.yaml
I think it is ok to still use 8080/http on master node because it basically connects to itself. I only switched to https on worker's `kubelet` and worker's `kube-proxy`
See #285 
I checked that Nodes are ready (kubectl get nodes) and there are no additional problems in logs of kube-proxy.
> Switched to secured k8s API endpoint (#285)

- README.md
- Vagrantfile
- manifests/master-controller-manager.yaml
- manifests/master-proxy.yaml
- manifests/node-proxy.yaml
- master.yaml
- node.yaml
- plugins/calico/calico-rbac.yaml
- plugins/calico/calico.yaml
- plugins/calico/calico.yaml.tmpl
This PR introduces Calico v3.1, replacing flannel as the overlay network. The cluster CIDR is being changed to `192.168.0.0/16`, which is Calico's default. `{master,node}.yaml` also saw some minor adjustments in order to allow Calico to be properly installed and used.
3bb41db is a required fix fox the VMs to boot with recent CoreOS versions. It is included for ease of testing even though it is unrelated to Calico. Please let me know if you'd like a separate PR for that.
Closes #282.
Closes #208.
> Use Calico for cluster networking.

- README.md
- Vagrantfile
Vagrant 2.1.0 breaks the installation due to the introduction of triggers into the core. As such, we should require 2.1.1, which introduces a fix that allows existing project to continue using `vagrant-triggers`.
> Require Vagrant 2.1.1.

- README.md
- Vagrantfile
CoreDNS has been the default DNS provider for a while now and there are no reports of problems with it.
@bmcstdio sorry for making your life miserable with the reformatting of the Vagrant file.
> Remove kube-dns

- tls/make-certs-master.sh
While running `vagrant up`, the following error pops up even if RBAC is disabled:
```
Error from server (Forbidden): error when creating "temp/coredns-deployment.yaml": clusterroles.rbac.authorization.k8s.io "system:coredns" is forbidden: attempt to grant extra privileges: [PolicyRule{APIGroups:[""], Resources:["endpoints"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["endpoints"], Verbs:["watch"]} PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["watch"]} PolicyRule{APIGroups:[""], Resources:["pods"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["pods"], Verbs:["watch"]} PolicyRule{APIGroups:[""], Resources:["namespaces"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["namespaces"], …
```
> Fix RBAC privilege escalation errors.

- Vagrantfile
`vagrant up` currently fails in Windows due to a missing `calico.yaml` file. This PR aims at fixing this.
Closes #300.
> Fix missing calico.yaml in Windows.

- plugins/calico/calico-rbac.yaml
- plugins/calico/calico.yaml.tmpl
In preparation for a bump to Kubernetes 1.12.0, the Calico manifests need some love. I am taking on the opportunity to bump us to v3.2.3.
> Bump Calico to v3.2.3.
