README.md
master.yaml
node.yaml

It will automatically download latest kubernetes binaries on each boot

Grab latest k8s binaries automatically

---

README.md
latest/master.yaml
latest/node.yaml
master.yaml
node.yaml

Also upgraded to Kubernetes 0.9.2.
Closes #5

Merged work by Rimas Mocevicius

---

README.md
Vagrantfile

"en passant" dead code was trimmed and the Vagrantfile was made a bit
more idiomatic

adding parallels support

---

Vagrantfile

to match github.com/coreos/coreos-vagrant featurewise

add support for vmware workstation

---

node.yaml

This will server as the basis for container monitoring.

Added cAdvisor unit to node cloud-config

---

README.md

by popular demand simplify README presentation.

---

Vagrantfile

(does not induce any kind of functional change)

Vagrantfile ruby tweaks for coding style coherency and consistency.

---

master.yaml
node.yaml

this shouldn't had got in in 1st place :/.

drop unneeded nfs related cruft.

---

master.yaml

docker-cache container now restarts on failure.

---

README.md
Vagrantfile
master.yaml

Added cloud provider support.

---

Vagrantfile

Windows is not supported

---

dns/dns-controller.yaml.tmpl

Fix DNS integration

---

dns/dns-controller.yaml.tmpl

Fixed stupid naming conflict.

---

Vagrantfile

Since ruby Net::Http is required it can be used to check if nodes are up. 
This has some advantages:
- Removes the curl dependency, for systems without curl (also windows)
- It has a finite loop, so vagrant does not hang in a ```curl > /dev/null``` loop
- Number of runs can be adjusted if a system needs more time to come up.

replacing curl for ruby Net::HTTP

---

dns/dns-controller.yaml.tmpl
dns/dns-service.yaml

Waiting for a couple testers feedback before merging.

Move DNS to API v1beta3 and upgrade kube2dns image.

---

README.md
Vagrantfile

Just waiting on release notes in order to merge this.

Upgraded to Kubernetes v0.17.0. 

---

Vagrantfile
master.yaml
node.yaml
setup.tmpl

I'm trying to run a Kubernetes cluster behind corporate proxy. I still have some problems, since for some reason **vagrantfile-user-data** is not invoked and my changes do not apply.

Run kubernetes cluster behind http proxy

---

Vagrantfile

Added KUBERNETES_MASTER env variable when creating dns

---

README.md
Vagrantfile
dns/dns-controller.yaml.tmpl
dns/dns-service.yaml
master.yaml

Fixes #118 
Depends on https://github.com/GoogleCloudPlatform/kubernetes/issues/9531 to be merged.

Upgraded to Kubernetes 0.19.0 and API v1.

---

Vagrantfile
master.yaml

GoogleCloudPlatform/kubernetes#10370

controller manager deprecated flags are removed in kubernetes 0.21.0

---

master.yaml

Removed deprecated apiserver flag public_address_override in favor of bind-address.

---

setup.tmpl

the check looks up the installation and compares its version. will only skip if nothing would change

added check to existing installation, fixes issue #154

---

Vagrantfile

The vagrantfile is missing the "system" command before running these commands.

kubectl fails to setup cluster/context.

---

manifests/master-controller-manager.yaml
manifests/master-proxy.yaml

fix controller and proxy static pod

---

Vagrantfile

In my opinion the update channel is wrong and will result in "valpha" in this case.

Fixed update channel

---

Vagrantfile

I had renamed `dashboard-controller.yaml` but forgot to update references to it on `Vagrantfile`.

Fix references to 'dashboard-controller.yaml'.

---

plugins/dashboard/dashboard-deployment.yaml

Not as fresh as Kubernetes 1.7.3, but still... 🙂

Upgrade 'kubernetes-dashboard' to version 1.6.3.

---

README.md
Vagrantfile

fix Vagrantfile bugs and add some useful tips: as files changed.

fix Vagrantfile bugs and add some useful tips
